name: 🐞 Bug Report
description: Report an unexpected error or behavior in the Run App
title: "[Bug] "
labels: [bug, needs-triage]
assignees: [shivanandpt]

body:
  - type: markdown
    attributes:
      value: |
        Please fill out the following form to help us diagnose and fix the issue.

  - type: input
    id: bug_summary
    attributes:
      label: 🐛 Bug Summary
      description: A short description of what went wrong.
      placeholder: e.g., App crashes when opening Training Plan screen
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: 🔁 Steps to Reproduce
      description: Step-by-step instructions to recreate the bug.
      placeholder: |
        1. Go to HomeScreen
        2. Tap on Training Plan
        3. Observe the error or crash
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: 🤔 Expected Behavior
      description: What did you expect to happen?
      placeholder: The training plan screen should load with personalized sessions.
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: 😵 Actual Behavior
      description: What actually happened?
      placeholder: App shows a blank screen and crashes.
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: 📱 Platform
      description: Where did this issue occur?
      options:
        - Android
        - iOS
        - Both
    validations:
      required: true

  - type: input
    id: app_version
    attributes:
      label: 🧾 App Version
      description: Version number of the app where this issue occurred.
      placeholder: e.g., v1.0.2
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: 🧪 Logs / Screenshots
      description: Add error logs, screenshots, or crash traces (if available).
      placeholder: Paste logs or upload screenshots
    validations:
      required: false

  - type: checkboxes
    id: testing_checklist
    attributes:
      label: ✅ Testing Checklist
      options:
        - label: Reproduced on Android
        - label: Reproduced on iOS
        - label: Regression from a previous version
        - label: Verified with latest code

  - type: textarea
    id: related
    attributes:
      label: 📎 Related Issues
      description: Link any related issues or pull requests.
      placeholder: e.g., Related to #123
    validations:
      required: false
